### PR TITLE
updates

### PR DESCRIPTION
**Pull request by baskinburak**
Hey I beautified  the website a bit. It looks like this now:

Screenshot from 2019-03-13 19-15-24

### CODE REVIEW

**Comment by gonzaiva** [comment]
Awesome changes @baskinburak, although I may change some of the fonts. Did you use a tool for this?
Also, does this scales well in other screen sizes?

**Comment by baskinburak** [comment]
it is only bootstrap. fonts are directly in the fonts directory. yes it scales. check images.
Screenshot from 2019-03-13 19-27-09
Screenshot from 2019-03-13 19-27-21
Screenshot from 2019-03-13 19-22-50

**Comment by baskinburak** [comment]
And lastly, colors are from these two palettes: https://colorhunt.co/palette/2763, https://colorhunt.co/palette/140436

**Comment by gonzaiva** [comment]
I did some changes m8, what do you think?

**Comment by gonzaiva** [comment]
Ups, I think new font is messing with the nav bar in mobile view.

**Comment by baskinburak** [comment]
@media (max-width: 575.98px) {
    a.navbar-brand {
      font-size:1.2em !important;
    }
  }

**Comment by baskinburak** [comment]
other than that seems good to me

**Comment by gonzaiva** [comment]
Awesome, thanks Baskin, you're da best!

**Comment by baskinburak** [comment]
cheers <3

**Pull request merged**
